# Generated by Django 3.2 on 2022-01-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220115_1808'),
        ('users', '0002_auto_20220115_1936'),
    ]

    operations = [
    ]
