# Generated by Django 3.2 on 2022-01-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_auto_20220115_1808_0002_auto_20220115_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/defaultPhoto.png', null=True, upload_to='users_photo', verbose_name='Фотография'),
        ),
    ]
