# Generated by Django 3.2.4 on 2021-11-25 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='web.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
