# Generated by Django 3.2.4 on 2021-11-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211126_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='favourite_vacancies',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_vacancies', to='web.Vacancy'),
        ),
        migrations.AlterField(
            model_name='student',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='web.Project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='web.Skills'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats', to='web.Chat', verbose_name='Чат'),
        ),
    ]
