# Generated by Django 3.2.4 on 2021-11-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/media/default_user_photo.jpg', null=True, upload_to='users_photo', verbose_name='Фотография'),
        ),
    ]
