# Generated by Django 3.2.4 on 2021-11-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=24, unique=True, verbose_name='Никнейм'),
        ),
    ]
