# Generated by Django 3.2.4 on 2021-11-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
